include: package:flutter_lints/flutter.yaml

linter:
  rules:
    always_use_package_imports: true
    eol_at_end_of_file: true
    prefer_single_quotes: true
    sort_pub_dependencies: true
    unnecessary_await_in_return: true
