name: search_github_repository
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  widgetbook: ^3.8.1
  widgetbook_annotation: ^3.1.0

dev_dependencies:
  build_runner: ^2.4.12
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  widgetbook_generator: ^3.8.0

flutter:
  uses-material-design: true
